### PR TITLE
Add audio options

### LINKED ISSUE #74: (1.12) Add config option to disable music
We use the Ambience - Extras mod to add our own music. We'd like to add music to the boss fights but need the original aether music to be disabled.

Thank you!

### PR DESCRIPTION
**Pull request by democat3457**
This pull request adds config options for the audio handler, including options for aether-dimensional music and menu music, if the menu is enabled. This pull request also refactors AetherMusicHandler.java and prevents redundant method calls by checking if the values are not `null` before setting them to `null`.

Fixes #74.

By submitting this pull request, I agree to the Contributor License Agreement under `CONTRIBUTING.md`.

### CODE REVIEW

**Comment by CalaMariGold** [comment]
Can this be merged and uploaded to CurseForge?

**Comment by democat3457** [comment]
bump

**Comment by bconlon1** [comment]
Apologies for taking so long to merge this.

**Comment by bconlon1** [comment]
Been busy with porting the mod so I haven't had time to get out a release but there might be one soon with the couple of bug fixes implemented since the last release, including this one.

**Pull request merged**
