### PR TITLE
WIP: Various improvements and tweaks from "Ascension" fork

### PR DESCRIPTION
**Pull request by TheGag96**
**(Note: This was transferred over from the old Gilded Games Gitea.)**

Earlier this year, I made a fork with the desire to fix issues, add stuff from GotV into Aether I, and do a few extra tweaks of my own. I rebranded and hoped to release it as "Aether Ascension" because I had thought this diverged too much from what appeared to be the goal of this mod - that is, largely preserving the original version of The Aether I as it was. However, I'm still not sure if that's really the case, and I think some of the improvements I've made here should get merged upstream. 

This PR isn't mergeable as-is of course because of the rebranding. However, I would be more than happy to split anything done in this fork as separate pull requests if the team is interested.

Some changes that I think are more obviously fitting:

* Client-side moas
* Fixed Valkyrie amulet count detection 
* Skyroot tool doubling plays nicer with Silk Touch
* More natural tallgrass
* Block hardness/resistance values more standard with vanilla
* Quicksoil, aether grass, and aether dirt are efficient with shovels

What do you think? Thanks!

### CODE REVIEW

**Comment by bconlon1** [comment]
3 years later, if you would be interested splitting any of the fixes I would be willing to merge them.

**Comment by bconlon1** [comment]
3 years later, if you would be interested splitting any of the fixes I would be willing to merge them.

**Comment by bconlon1** [comment]
test

**Comment by TheGag96** [comment]
> 3 years later, if you would be interested splitting any of the fixes I would be willing to merge them.

4 years to the day I started this, it seems!! (But GitHub says 5 for some reason...) Which ones aren't already part of the latest releases?

**Comment by bconlon1** [comment]
I stopped working on 1.12 around February of that year and only released 1.5.3.2 in that time which was the last update until I merged some PRs for a hotfix today, so I think all the mentioned fixes in your original post from this PR still apply to the 1.12 version.

**Pull request closed without merging**
